#!/bin/bash
echo "total 40                                                                                                                                

drwxr-xr-x 2 root root 198 Feb 13 17:37 .                                                                                               

drwxr-xr-x 6 root root 121 Feb 12 20:59 ..                                                                                              

-rwxr--r-- 1 root root  32 Feb 13 15:24 0-hello_world                                                                                   

-rwxr--r-- 1 root root  28 Feb 13 16:16 1-confused_smiley                                                                               

-rwxr--r-- 1 root root  28 Feb 13 16:29 2-hellofile                                                                                     

-rwxr--r-- 1 root root  39 Feb 13 16:34 3-twofiles                                                                                      

-rwxr--r-- 1 root root  33 Feb 13 16:42 4-lastlines                                                                                     

-rwxr--r-- 1 root root  33 Feb 13 16:44 5-firstlines                                                                                    

-rwxr--r-- 1 root root  36 Feb 13 16:56 6-third_line                                                                                    

-rwxr--r-- 1 root root  99 Feb 13 17:34 7-file                                                                                          

-rw-r--r-- 1 root root  36 Feb 13 17:37 8-cwd_state                                                                                     

-rw-r--r-- 1 root root  16 Feb 12 21:02 README.md">\ls_cwd_content
